version: "3.7"

services:
  web:
    image: nginx:1.18 
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 
      - ./app/public:/app/public # 静的コンテンツをバインド

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: todo:rails
    tty: true
    ports:
      - 3000:3000
    working_dir: /app/todo
    volumes:
      - ./app:/app
    environment:
      TZ: "Asia/Tokyo"
      DB_USER: root
      DB_HOST: mysql
      DB_PASSWORD: secret
      DB_DATABASE: todo_rails

  mysql:
    image: mysql:8
    volumes:
      - mysql-rails:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todo_development
      TZ: "Asia/Tokyo"
      LANG: ja_JP.UTF-8
      LC_ALL: ja_JP.UTF-8

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret

volumes:
  mysql-rails: